### ISSUE TITLE
[Question] How to debug a custom Teams Tab if it fails to save its settings?

### ISSUE THREAD

**Issue by tscholze** [OfficeDev/microsoft-teams-sample-get-started#13]
** Please **
Please tell me (and / or) remove this issue if this type of issue is not allowed to post it here.

Hi folks,
thanks for helping me a lot in the past.
It would be great if you could give me a tip **how to debug** my Teams tab if it fails to store its settings. The browser's JavaScript error console does not log any errors. What's the best way to deep dive into this error?

As context, I added the related Stackoverflow question: http://stackoverflow.com/questions/43238722/microsoft-teams-tab-is-unable-to-save-settings-during-the-adding-to-a-channel

**Context:**

I try to write a simple Microsoft Teams tab that displays a feed list.
I'm able to side load my tab to Teams and to select it from the Channel "+" menu.

**Problem:**

If I want to save my settings, an error text appears that says "We couldn't save your tab settings. Please try again." There is no error in my browser's javascript error console.

**My config.html tab javascript code:**
    <script src="https://statics.teams.microsoft.com/sdk/v0.4/js/MicrosoftTeams.min.js"></script>
```
    <script type="text/javascript">
        microsoftTeams.initialize();
        microsoftTeams.settings.registerOnSaveHandler(function (saveEvent) {

            microsoftTeams.settings.setSettings({
                entityId: "example",
                contentUrl: "https://example.com/tab.html",
                suggestedDisplayName: "example",
                websiteUrl: "https://example.com",
                removeUrl: "https://example.com/remove.html"
            });

            saveEvent.notifySuccess();
        });

        function onClick() 
        {
            microsoftTeams.settings.setValidityState(true);
        }
    </script>
```
**My manifest.json**
```
    {
      "$schema": "https://statics.teams.microsoft.com/sdk/v0.4/manifest/MicrosoftTeams.schema.json",
      "manifestVersion": "0.4",
      "id": "ee90834a-d649-458d-a4e2-0b0f8d425c11",
      "version": "1.0",
      "name": "WINSider Community Deutschland",
      "developer": {
          "name": "WINSider Community Deutschland",   
          "websiteUrl": "https://windowscommunity.de",
          "privacyUrl": "https://windowscommunity.de/de/impressum/",
          "termsOfUseUrl": "http://windowscommunity.de/de/impressum/"
      },
      "tabs" : [{
        "id": "ee90834a-d649-458d-a4e2-0b0f8d425c11",
        "name": "WINSider Community",
        "description" : {
          "short": "WINsider article list as a tab",
          "full": "Summarizes the windowscommunity.de blog posts as a clickable list."
        },
        "icons": {
          "44": "icon44.png",
          "88": "icon88.png"
        },
        "accentColor" : "#37A3CF",
        "configUrl": "https://tscholze.github.io/public/teamstab/config.html",
        "canUpdateConfig": true
      }],
      "needsIdentity": false,
      "validDomains": [
          "*.github.io",
          "*.github.com",
          "*.googleapis.com",
          "*.microsoft.com",
          "*.rss2json.com",
          "*windowscommunity.de"
      ]
    }
```

**Comment by dfederm** [comment]
At a glance it looks like your `contentUrl`, `websiteUrl`, and `removeUrl` are using domains not in your `validDomains` list. This will cause the save to fail.

We'll look into how we can better expose tab save errors to developers.

**Comment by tscholze** [comment]
Good morning folks,
@dfederm the `example.org` urls were intended to work as anonym placeholder. Sorry for this mismatch. The contentUrl, websiteUrl, and removeUrl are linked to the `tscholze.github.io/.../page.html` stuff.

**Comment by dfederm** [comment]
@tscholze I just sideloaded your manifest from your github and after fixing the validation problem (the tab name is too long btw) it looks like the problem is the `websiteUrl`. You are providing `https://www.windowscommunity.de` but in your manifest you have `*windowscommunity.de` in the `validDomains`. The `validDomains` field doesn't support arbitrary wildcard patterns but instead more like DNS wildcarding. After changing the value to `*.windowscommunity.de` (notice the "." after the "*") I was able to get it to work!

For future reference, and until we do a better job at exposing these errors to developers, here are the steps I took to figure out the problem. Beware as it involves digging through minified code and basically knowing exactly what to look for, but might be helpful to identify this specific class of problem in the future.
1. Sideloaded the tab and attempted to add it. Notice that it failed to save.
2. Opened Chome devtools and found the 3-app.min-*.js file
3. Pretty printed the file to make it semi-readable
4. Did a find for `handleSaveSuccess` and put breakpoints as seen below
5. Clicked the Save button again.
6. `c` here (minified ofc) is a list of promises which do validation on the settings provided by the tab. In the `all` promise result, `a` is the list of promise results, and as seen here it's the promise at index 2 which failed, which has to do with `websiteUrl`, so we know that Teams is considering it invalid.
7. From there I just manually inspected the `websiteUrl` provided and the manifest to find the problem.

![image](https://cloud.githubusercontent.com/assets/6445614/25347314/58254ab6-28cf-11e7-9f81-9c392fa47540.png)

**Comment by tscholze** [comment]
@dfederm You are my real hero of the day! 
Thanks a lot for your effort to help a simple "try to get into Microsoft Teams Tab / Bot"-guy like me.

**Comment by misbach** [comment]
@dfederm I'm having trouble finding the 3-app.min-*.js in the debugger. Where is it loaded from?

**Comment by dfederm** [comment]
@misbach Oops, sorry, the full path is https://statics.teams.microsoft.com/hashedjs/3-app.min-*.js

![image](https://cloud.githubusercontent.com/assets/6445614/25411702/0e1cc0d4-29d3-11e7-952a-1a09ab7cfd64.png)

For future reference, in Chrome if you do Ctrl+P you can search for the filename:
![image](https://cloud.githubusercontent.com/assets/6445614/25411745/4a59ea0e-29d3-11e7-9e83-020f884f8fb6.png)

**Comment by misbach** [comment]
@dfederm Thanks, that helped, however in my case the handleSaveSuccess() function isn't even getting called. Do you mind checking out my [tab](https://github.com/misbach/MSTEamsTab/blob/master/package/tab.zip)?

**Comment by dfederm** [comment]
@misbach I sideloaded your tab and was able to hit the breakpoints in `handleSaveSuccess`. Looks like the problem is similar as the `websiteUrl` is `https://familysearch.org/apps` while the manifest has `*.familysearch.org` in the `validDomains`.

Changing the `websiteUrl` to `https://www.familysearch.org/apps` (prepend a subdomain) or changing the `validDomains` to contain `familysearch.org` (without the `*.` subdomain wildcard) should fix it.

**Comment by misbach** [comment]
@dfederm Thank you! It was the subdomain issue.

**Comment by NischaiV** [comment]
> @misbach Oops, sorry, the full path is https://statics.teams.microsoft.com/hashedjs/3-app.min-*.js
> 
> ![image](https://cloud.githubusercontent.com/assets/6445614/25411702/0e1cc0d4-29d3-11e7-952a-1a09ab7cfd64.png)
> 
> For future reference, in Chrome if you do Ctrl+P you can search for the filename:
> ![image](https://cloud.githubusercontent.com/assets/6445614/25411745/4a59ea0e-29d3-11e7-9e83-020f884f8fb6.png)

I am having similar issue and I checked for the mentioned fixes, but it does not solve it. Also, I have 3 files - attaching the screenshot along with.
![files](https://user-images.githubusercontent.com/15137356/63588570-2146a900-c5a7-11e9-98de-72d8425a3016.PNG)

**Comment by NischaiV** [comment]
Ok, I think I figured it out. Thanks for giving this elaborate description. :)
